export const people = [
  {
    id: "serenity",
    name: "Serenity",
    handle: "@aleabitoreddit",
    category: "AI/Semi Supply Chain",
    country: "US",
    avatar: "SE",
    avatarUrl: "https://unavatar.io/x/aleabitoreddit",
    bio: "Viral X researcher focused on AI infrastructure bottlenecks and overlooked supply-chain equities.",
    featured: true,
    sources: ["https://x.com/aleabitoreddit"]
  },
  {
    id: "citrini",
    name: "Citrini",
    handle: "@citrini",
    category: "Thematic Research",
    country: "US",
    avatar: "CI",
    avatarUrl: "https://unavatar.io/x/citrini",
    bio: "Cross-asset thematic research publisher known for viral AI and macro market notes.",
    featured: true,
    sources: ["https://x.com/citrini", "https://www.citriniresearch.com/"]
  },
  {
    id: "arthur_hayes",
    name: "Arthur Hayes",
    handle: "@CryptoHayes",
    category: "Crypto Macro",
    country: "Global",
    avatar: "AH",
    avatarUrl: "https://unavatar.io/x/CryptoHayes",
    bio: "Crypto investor and essayist whose market views often become tradeable crypto theses.",
    featured: true,
    sources: ["https://x.com/CryptoHayes", "https://cryptohayes.medium.com/"]
  },
  {
    id: "tom_lee",
    name: "Tom Lee",
    handle: "@fundstrat",
    category: "Market Strategist",
    country: "US",
    avatar: "TL",
    avatarUrl: "https://unavatar.io/x/fundstrat",
    bio: "Fundstrat co-founder and public markets strategist known for bullish equity and crypto calls.",
    featured: true,
    sources: ["https://x.com/fundstrat", "https://fundstrat.com/"]
  },
  {
    id: "jeon_wonju",
    name: "전원주",
    handle: "",
    category: "Celebrity Investor",
    country: "KR",
    avatar: "전",
    avatarUrl: "https://img.youtube.com/vi/yDkYvZhTYYI/hqdefault.jpg",
    bio: "Korean celebrity investor known for long-term SK hynix ownership stories.",
    featured: true,
    sources: ["https://www.hankookilbo.com/news/article/A2026013010280005478"]
  },
  {
    id: "jukan",
    name: "Jukan",
    handle: "@jukan05",
    category: "AI/Semi Commentary",
    country: "Global",
    avatar: "JU",
    avatarUrl: "https://unavatar.io/x/jukan05",
    bio: "X account tracking semiconductors, AI infrastructure, and supply-chain signals.",
    featured: false,
    sources: ["https://x.com/jukan05"]
  },
  {
    id: "threadguy",
    name: "threadguy",
    handle: "@notthreadguy",
    category: "Crypto Media",
    country: "US",
    avatar: "TG",
    avatarUrl: "https://unavatar.io/x/notthreadguy",
    bio: "Crypto media personality covering markets, culture, and financialization.",
    featured: false,
    sources: ["https://x.com/notthreadguy", "https://www.youtube.com/@notthreadguy"]
  },
  {
    id: "ansem",
    name: "Ansem",
    handle: "@blknoiz06",
    category: "Crypto Trader",
    country: "US",
    avatar: "AN",
    avatarUrl: "https://unavatar.io/x/blknoiz06",
    bio: "Crypto trader and market commentator known for viral CT calls.",
    featured: false,
    sources: ["https://x.com/blknoiz06"]
  },
  {
    id: "michael_saylor",
    name: "Michael Saylor",
    handle: "@saylor",
    category: "Bitcoin Executive",
    country: "US",
    avatar: "MS",
    avatarUrl: "https://unavatar.io/x/saylor",
    bio: "Executive and public Bitcoin advocate.",
    featured: false,
    sources: ["https://x.com/saylor"]
  },
  {
    id: "jim_cramer",
    name: "Jim Cramer",
    handle: "",
    category: "TV Host",
    country: "US",
    avatar: "JC",
    avatarUrl: "https://unavatar.io/x/jimcramer",
    bio: "CNBC host and public markets commentator.",
    featured: false,
    sources: ["https://www.cnbc.com/jim-cramer/"]
  },
  {
    id: "jeon_ingu",
    name: "전인구",
    handle: "",
    category: "YouTube Investor",
    country: "KR",
    avatar: "전",
    avatarUrl: "https://unavatar.io/youtube/moneydo",
    bio: "전인구경제연구소를 운영하는 한국 투자 유튜브 인플루언서입니다.",
    featured: true,
    sources: ["https://www.youtube.com/@moneydo"]
  },
  {
    id: "syuka",
    name: "슈카월드",
    handle: "",
    category: "Finance YouTube",
    country: "KR",
    avatar: "슈",
    avatarUrl: "https://unavatar.io/youtube/syukaworld",
    bio: "경제와 시장 이슈를 대중적으로 해설하는 한국 경제 유튜브 채널입니다.",
    featured: true,
    sources: ["https://www.youtube.com/@syukaworld"]
  },
  {
    id: "threepro",
    name: "삼프로TV",
    handle: "",
    category: "Finance Media",
    country: "KR",
    avatar: "삼",
    avatarUrl: "https://logo.clearbit.com/3protv.com",
    bio: "국내 주식과 매크로를 다루는 한국 경제/투자 미디어입니다.",
    featured: true,
    sources: ["https://www.youtube.com/channel/UChlv4GSd7OQl3js-jkLOnFA", "https://apps.3protv.com/"]
  }
];

export const assets = {
  RPI: { name: "Raspberry Pi Holdings", type: "stock", exchange: "LSE", yahoo: "RPI.L", logoUrl: "https://logo.clearbit.com/raspberrypi.com" },
  AXTI: { name: "AXT Inc.", type: "stock", exchange: "NASDAQ", yahoo: "AXTI", logoUrl: "https://logo.clearbit.com/axt.com" },
  SIVE: { name: "Sivers Semiconductors", type: "stock", exchange: "STO", yahoo: "SIVE.ST", logoUrl: "https://logo.clearbit.com/sivers-semiconductors.com" },
  XFAB: { name: "X-FAB Silicon Foundries", type: "stock", exchange: "EPA", yahoo: "XFAB.PA", logoUrl: "https://logo.clearbit.com/xfab.com" },
  BTC: { name: "Bitcoin", type: "crypto", coingecko: "bitcoin", logoUrl: "https://assets.coingecko.com/coins/images/1/large/bitcoin.png" },
  ETH: { name: "Ethereum", type: "crypto", coingecko: "ethereum", logoUrl: "https://assets.coingecko.com/coins/images/279/large/ethereum.png" },
  HYPE: { name: "Hyperliquid", type: "crypto", coingecko: "hyperliquid", logoUrl: "https://assets.coingecko.com/coins/images/50882/large/hyperliquid.jpg" },
  BNB: { name: "BNB", type: "crypto", coingecko: "binancecoin", logoUrl: "https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png" },
  XRP: { name: "XRP", type: "crypto", coingecko: "ripple", logoUrl: "https://assets.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png" },
  SOL: { name: "Solana", type: "crypto", coingecko: "solana", logoUrl: "https://assets.coingecko.com/coins/images/4128/large/solana.png" },
  TRX: { name: "TRON", type: "crypto", coingecko: "tron", logoUrl: "https://assets.coingecko.com/coins/images/1094/large/tron-logo.png" },
  DOGE: { name: "Dogecoin", type: "crypto", coingecko: "dogecoin", logoUrl: "https://assets.coingecko.com/coins/images/5/large/dogecoin.png" },
  ZEC: { name: "Zcash", type: "crypto", coingecko: "zcash", logoUrl: "https://assets.coingecko.com/coins/images/486/large/circle-zcash-color.png" },
  XLM: { name: "Stellar", type: "crypto", coingecko: "stellar", logoUrl: "https://assets.coingecko.com/coins/images/100/large/Stellar_symbol_black_RGB.png" },
  XMR: { name: "Monero", type: "crypto", coingecko: "monero", logoUrl: "https://assets.coingecko.com/coins/images/69/large/monero_logo.png" },
  ADA: { name: "Cardano", type: "crypto", coingecko: "cardano", logoUrl: "https://assets.coingecko.com/coins/images/975/large/cardano.png" },
  LINK: { name: "Chainlink", type: "crypto", coingecko: "chainlink", logoUrl: "https://assets.coingecko.com/coins/images/877/large/chainlink-new-logo.png" },
  AVAX: { name: "Avalanche", type: "crypto", coingecko: "avalanche-2", logoUrl: "https://assets.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png" },
  SUI: { name: "Sui", type: "crypto", coingecko: "sui", logoUrl: "https://assets.coingecko.com/coins/images/26375/large/sui-ocean-square.png" },
  NEAR: { name: "NEAR Protocol", type: "crypto", coingecko: "near", logoUrl: "https://assets.coingecko.com/coins/images/10365/large/near.jpg" },
  APT: { name: "Aptos", type: "crypto", coingecko: "aptos", logoUrl: "https://assets.coingecko.com/coins/images/26455/large/aptos_round.png" },
  WLD: { name: "Worldcoin", type: "crypto", coingecko: "worldcoin-wld", logoUrl: "https://assets.coingecko.com/coins/images/31069/large/worldcoin.jpeg" },
  SPX: { name: "S&P 500", type: "index", yahoo: "^GSPC", logoUrl: "https://logo.clearbit.com/spglobal.com" },
  AAPL: { name: "Apple", type: "stock", exchange: "NASDAQ", yahoo: "AAPL", logoUrl: "https://logo.clearbit.com/apple.com" },
  MSFT: { name: "Microsoft", type: "stock", exchange: "NASDAQ", yahoo: "MSFT", logoUrl: "https://logo.clearbit.com/microsoft.com" },
  NVDA: { name: "Nvidia", type: "stock", exchange: "NASDAQ", yahoo: "NVDA", logoUrl: "https://logo.clearbit.com/nvidia.com" },
  AMZN: { name: "Amazon", type: "stock", exchange: "NASDAQ", yahoo: "AMZN", logoUrl: "https://logo.clearbit.com/amazon.com" },
  GOOGL: { name: "Alphabet", type: "stock", exchange: "NASDAQ", yahoo: "GOOGL", logoUrl: "https://logo.clearbit.com/abc.xyz" },
  META: { name: "Meta Platforms", type: "stock", exchange: "NASDAQ", yahoo: "META", logoUrl: "https://logo.clearbit.com/meta.com" },
  AVGO: { name: "Broadcom", type: "stock", exchange: "NASDAQ", yahoo: "AVGO", logoUrl: "https://logo.clearbit.com/broadcom.com" },
  TSLA: { name: "Tesla", type: "stock", exchange: "NASDAQ", yahoo: "TSLA", logoUrl: "https://logo.clearbit.com/tesla.com" },
  TSM: { name: "TSMC", type: "stock", exchange: "NYSE", yahoo: "TSM", logoUrl: "https://logo.clearbit.com/tsmc.com" },
  BRK_B: { name: "Berkshire Hathaway", type: "stock", exchange: "NYSE", yahoo: "BRK-B", logoUrl: "https://logo.clearbit.com/berkshirehathaway.com" },
  JPM: { name: "JPMorgan Chase", type: "stock", exchange: "NYSE", yahoo: "JPM", logoUrl: "https://logo.clearbit.com/jpmorganchase.com" },
  V: { name: "Visa", type: "stock", exchange: "NYSE", yahoo: "V", logoUrl: "https://logo.clearbit.com/visa.com" },
  LLY: { name: "Eli Lilly", type: "stock", exchange: "NYSE", yahoo: "LLY", logoUrl: "https://logo.clearbit.com/lilly.com" },
  ORCL: { name: "Oracle", type: "stock", exchange: "NYSE", yahoo: "ORCL", logoUrl: "https://logo.clearbit.com/oracle.com" },
  NFLX: { name: "Netflix", type: "stock", exchange: "NASDAQ", yahoo: "NFLX", logoUrl: "https://logo.clearbit.com/netflix.com" },
  AMD: { name: "AMD", type: "stock", exchange: "NASDAQ", yahoo: "AMD", logoUrl: "https://logo.clearbit.com/amd.com" },
  PLTR: { name: "Palantir", type: "stock", exchange: "NASDAQ", yahoo: "PLTR", logoUrl: "https://logo.clearbit.com/palantir.com" },
  MSTR: { name: "Strategy", type: "stock", exchange: "NASDAQ", yahoo: "MSTR", logoUrl: "https://logo.clearbit.com/strategy.com" },
  WBD: { name: "Warner Bros. Discovery", type: "stock", exchange: "NASDAQ", yahoo: "WBD", logoUrl: "https://logo.clearbit.com/warnerbrosdiscovery.com" },
  "005930.KS": { name: "삼성전자", type: "stock", exchange: "KRX", yahoo: "005930.KS", logoUrl: "https://logo.clearbit.com/samsung.com" },
  "373220.KS": { name: "LG에너지솔루션", type: "stock", exchange: "KRX", yahoo: "373220.KS", logoUrl: "https://logo.clearbit.com/lgensol.com" },
  "207940.KS": { name: "삼성바이오로직스", type: "stock", exchange: "KRX", yahoo: "207940.KS", logoUrl: "https://logo.clearbit.com/samsungbiologics.com" },
  "005490.KS": { name: "POSCO홀딩스", type: "stock", exchange: "KRX", yahoo: "005490.KS", logoUrl: "https://logo.clearbit.com/posco-inc.com" },
  "068270.KS": { name: "셀트리온", type: "stock", exchange: "KRX", yahoo: "068270.KS", logoUrl: "https://logo.clearbit.com/celltrion.com" },
  "012330.KS": { name: "현대모비스", type: "stock", exchange: "KRX", yahoo: "012330.KS", logoUrl: "https://logo.clearbit.com/mobis.co.kr" },
  "105560.KS": { name: "KB금융", type: "stock", exchange: "KRX", yahoo: "105560.KS", logoUrl: "https://logo.clearbit.com/kbfg.com" },
  "055550.KS": { name: "신한지주", type: "stock", exchange: "KRX", yahoo: "055550.KS", logoUrl: "https://logo.clearbit.com/shinhangroup.com" },
  "035420.KS": { name: "NAVER", type: "stock", exchange: "KRX", yahoo: "035420.KS", logoUrl: "https://logo.clearbit.com/naver.com" },
  "035720.KS": { name: "카카오", type: "stock", exchange: "KRX", yahoo: "035720.KS", logoUrl: "https://logo.clearbit.com/kakaocorp.com" },
  "005380.KS": { name: "현대차", type: "stock", exchange: "KRX", yahoo: "005380.KS", logoUrl: "https://logo.clearbit.com/hyundai.com" },
  "051910.KS": { name: "LG화학", type: "stock", exchange: "KRX", yahoo: "051910.KS", logoUrl: "https://logo.clearbit.com/lgchem.com" },
  "006400.KS": { name: "삼성SDI", type: "stock", exchange: "KRX", yahoo: "006400.KS", logoUrl: "https://logo.clearbit.com/samsungsdi.com" },
  "028260.KS": { name: "삼성물산", type: "stock", exchange: "KRX", yahoo: "028260.KS", logoUrl: "https://logo.clearbit.com/samsungcnt.com" },
  "086790.KS": { name: "하나금융지주", type: "stock", exchange: "KRX", yahoo: "086790.KS", logoUrl: "https://logo.clearbit.com/hanaw.com" },
  "034020.KS": { name: "두산에너빌리티", type: "stock", exchange: "KRX", yahoo: "034020.KS", logoUrl: "https://logo.clearbit.com/doosanenerbility.com" },
  "042660.KS": { name: "한화오션", type: "stock", exchange: "KRX", yahoo: "042660.KS", logoUrl: "https://logo.clearbit.com/hanwhaocean.com" },
  "003670.KS": { name: "포스코퓨처엠", type: "stock", exchange: "KRX", yahoo: "003670.KS", logoUrl: "https://logo.clearbit.com/poscofuturem.com" },
  "096770.KS": { name: "SK이노베이션", type: "stock", exchange: "KRX", yahoo: "096770.KS", logoUrl: "https://logo.clearbit.com/skinnovation.com" },
  "066570.KS": { name: "LG전자", type: "stock", exchange: "KRX", yahoo: "066570.KS", logoUrl: "https://logo.clearbit.com/lge.co.kr" },
  "000660.KS": { name: "SK하이닉스", type: "stock", exchange: "KRX", yahoo: "000660.KS", logoUrl: "https://companieslogo.com/img/orig/000660.KS-fcb3503e.png?t=1720244489" },
  CITRINDEX: { name: "Citrini Core Thematic Portfolio", type: "basket", logoUrl: "https://unavatar.io/x/citrini" },
  AI_INFRA: { name: "AI Infrastructure Basket", type: "basket", logoUrl: "https://logo.clearbit.com/nvidia.com" }
};

const baseSeedCalls = [
  {
    id: "call_serenity_rpi",
    personId: "serenity",
    symbol: "RPI",
    calledAt: "2026-02-16",
    callType: "bullish_call",
    quote: "Fun Trade Idea: Long $RPI (Raspberry Pi)",
    sourceUrl: "https://x.com/aleabitoreddit/status/2051628401354785026",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 96,
    entryPrice: 280,
    currentPrice: 812,
    currency: "GBp"
  },
  {
    id: "call_serenity_core_longs",
    personId: "serenity",
    symbol: "SIVE",
    calledAt: "2026-06-16",
    callType: "position_disclosure",
    quote: "Core European longs recap included $SIVE, $LPK, $SOI, $RPI, $IQE, $XFAB.",
    sourceUrl: "https://x.com/aleabitoreddit/status/2066535221554733278",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 79,
    entryPrice: 8.2,
    currentPrice: 11.7,
    currency: "SEK"
  },
  {
    id: "call_citrini_citrindex",
    personId: "citrini",
    symbol: "CITRINDEX",
    calledAt: "2023-05-31",
    callType: "portfolio_disclosure",
    quote: "Citrindex tracks Citrini Research's core thematic model portfolio.",
    sourceUrl: "https://www.citriniresearch.com/p/citrindex-one-year-anniversary",
    sourcePlatform: "Substack",
    status: "seed_verified",
    viralScore: 72,
    entryPrice: 100,
    currentPrice: 200.57,
    currency: "index"
  },
  {
    id: "call_citrini_ai_infra",
    personId: "citrini",
    symbol: "AI_INFRA",
    calledAt: "2026-02-24",
    callType: "theme_call",
    quote: "AI disruption view pointed investors toward less-disruptable sectors such as semiconductors and energy.",
    sourceUrl: "https://x.com/citrini/status/2025668400396349476",
    sourcePlatform: "X",
    status: "seed_candidate",
    viralScore: 91,
    entryPrice: 100,
    currentPrice: 128.4,
    currency: "basket"
  },
  {
    id: "call_hayes_btc_1m",
    personId: "arthur_hayes",
    symbol: "BTC",
    calledAt: "2025-05-01",
    callType: "bullish_call",
    quote: "Arthur Hayes repeated his prediction that Bitcoin could reach $1 million by 2028.",
    sourceUrl: "https://www.theblock.co/post/352482/arthur-hayes-repeats-1-million-bitcoin-prediction-by-2028",
    sourcePlatform: "Article",
    status: "seed_verified",
    viralScore: 86,
    entryPrice: 96900,
    currentPrice: 104200,
    currency: "USD"
  },
  {
    id: "call_hayes_holy_trinity",
    personId: "arthur_hayes",
    symbol: "NEAR",
    calledAt: "2026-05-24",
    callType: "position_disclosure",
    quote: "When you are in position, trading is easy, sit back and watch number go up. $HYPE, $ZEC, $NEAR the holy trinity!",
    sourceUrl: "https://x.com/CryptoHayes/status/2057739953656737990",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 89,
    entryPrice: 2.32,
    currentPrice: 3.05,
    currency: "USD"
  },
  {
    id: "call_tom_lee_crypto_spring",
    personId: "tom_lee",
    symbol: "BTC",
    calledAt: "2026-05-05",
    callType: "bullish_call",
    quote: "$BTC $ETH Crypto spring is here",
    sourceUrl: "https://x.com/fundstrat/status/2055147947898065340",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 84,
    entryPrice: 94200,
    currentPrice: 104200,
    currency: "USD"
  },
  {
    id: "call_tom_lee_spx",
    personId: "tom_lee",
    symbol: "SPX",
    calledAt: "2025-12-11",
    callType: "bullish_call",
    quote: "Tom Lee projected the S&P 500 to hit 7,700 by the end of 2026.",
    sourceUrl: "https://www.coindesk.com/markets/2026/01/05/tom-lee-calls-for-a-new-bitcoin-ath-in-january-while-warning-of-a-volatile-2026",
    sourcePlatform: "CoinDesk",
    status: "seed_verified",
    viralScore: 78,
    entryPrice: 6880,
    currentPrice: 7023,
    currency: "USD"
  },
  {
    id: "call_cramer_wbd_loss",
    personId: "jim_cramer",
    symbol: "WBD",
    calledAt: "2022-04-11",
    callType: "bullish_call",
    quote: "Jim Cramer highlighted Warner Bros. Discovery as a post-merger media opportunity.",
    sourceUrl: "https://www.cnbc.com/jim-cramer/",
    sourcePlatform: "CNBC",
    status: "seed_candidate",
    viralScore: 61,
    entryPrice: 24.78,
    currentPrice: 10.92,
    currency: "USD"
  },
  {
    id: "call_cramer_tsla_loss",
    personId: "jim_cramer",
    symbol: "TSLA",
    calledAt: "2021-11-05",
    callType: "bullish_call",
    quote: "Cramer was publicly positive on Tesla near a high-volatility period for the stock.",
    sourceUrl: "https://www.cnbc.com/jim-cramer/",
    sourcePlatform: "CNBC",
    status: "seed_candidate",
    viralScore: 67,
    entryPrice: 407.36,
    currentPrice: 184.20,
    currency: "USD"
  },
  {
    id: "call_citrini_nvda_loss",
    personId: "citrini",
    symbol: "NVDA",
    calledAt: "2026-06-01",
    callType: "bullish_call",
    quote: "AI infrastructure remains a core thematic exposure, though Nvidia has pulled back since the note.",
    sourceUrl: "https://x.com/citrini",
    sourcePlatform: "X",
    status: "seed_candidate",
    viralScore: 74,
    entryPrice: 212.08,
    currentPrice: 209.05,
    currency: "USD"
  },
  {
    id: "call_jeon_hynix_2011",
    personId: "jeon_wonju",
    symbol: "000660.KS",
    calledAt: "2011-01-01",
    callType: "portfolio_disclosure",
    quote: "?꾩썝二쇰뒗 SK?섏씠?됱뒪 二쇱떇??2011??珥?2留뚯썝???留ㅼ엯???꾩옱源뚯? 蹂댁쑀 以묒씠?쇨퀬 諛앺삍??",
    sourceUrl: "https://www.hankookilbo.com/news/article/A2026013010280005478",
    sourcePlatform: "?쒓뎅?쇰낫",
    status: "seed_verified",
    viralScore: 93,
    entryPrice: 20000,
    currentPrice: 2382000,
    currency: "KRW"
  },
  {
    id: "call_jeon_hynix_2021",
    personId: "jeon_wonju",
    symbol: "000660.KS",
    calledAt: "2021-01-26",
    callType: "position_disclosure",
    quote: "2021??諛⑹넚?먯꽌 SK?섏씠?됱뒪瑜?10???댁긽 蹂댁쑀 以묒씠?쇨퀬 諛앺삍??",
    sourceUrl: "https://economist.co.kr/article/view/ecn202601300004",
    sourcePlatform: "Economist Korea",
    status: "seed_verified",
    viralScore: 81,
    entryPrice: 128500,
    currentPrice: 2382000,
    currency: "KRW"
  },
  {
    id: "call_threadguy_worldcoin",
    personId: "threadguy",
    symbol: "WLD",
    calledAt: "2026-02-10",
    callType: "mention_candidate",
    quote: "There's a parallel universe where worldcoin was the best performing token ever.",
    sourceUrl: "https://x.com/notthreadguy/status/2017249158281732511",
    sourcePlatform: "X",
    status: "seed_candidate",
    viralScore: 54,
    entryPrice: 1.12,
    currentPrice: 1.36,
    currency: "USD"
  },
  {
    id: "call_saylor_btc",
    personId: "michael_saylor",
    symbol: "BTC",
    calledAt: "2024-02-26",
    callType: "portfolio_disclosure",
    quote: "MicroStrategy acquired an additional 3,000 BTC at an average price of $51,813 per bitcoin.",
    sourceUrl: "https://x.com/saylor/status/1762101030336999899",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 88,
    entryPrice: 51813,
    currentPrice: 104200,
    currency: "USD"
  }
];

const additionalCallTemplates = [
  ["serenity", "AXTI", "2026-01-08", 3.12, 5.64, "AI 怨듦툒留앹뿉??AXT瑜?援ъ“???섑삙 ?꾨낫濡??멸툒?덉뒿?덈떎.", "https://x.com/aleabitoreddit"],
  ["serenity", "XFAB", "2026-01-16", 5.7, 7.9, "?좊읇 諛섎룄泥??뚯슫?쒕━ ?몄텧濡?X-FAB???멸툒?덉뒿?덈떎.", "https://x.com/aleabitoreddit"],
  ["serenity", "NVDA", "2026-02-02", 188.4, 209.05, "AI ?명봽???듭떖 醫낅ぉ?쇰줈 ?붾퉬?붿븘瑜?諛섎났 ?멸툒?덉뒿?덈떎.", "https://x.com/aleabitoreddit"],
  ["serenity", "TSLA", "2026-03-12", 214.6, 184.2, "濡쒕낫?깆뒪/AI ?좏깮吏濡??뚯뒳?쇰? 愿李??꾨낫???щ졇?듬땲??", "https://x.com/aleabitoreddit"],
  ["serenity", "BTC", "2026-04-20", 88400, 104200, "?꾪뿕?먯궛 ?ы룊媛 援ш컙?먯꽌 鍮꾪듃肄붿씤???멸툒?덉뒿?덈떎.", "https://x.com/aleabitoreddit"],
  ["serenity", "ETH", "2026-04-21", 2940, 3820, "AI ?명봽?쇱? ?⑥껜???먯궛???④퍡 蹂대뒗 愿?먯뿉??ETH瑜??멸툒?덉뒿?덈떎.", "https://x.com/aleabitoreddit"],
  ["serenity", "005930.KS", "2026-03-04", 71300, 79200, "硫붾え由??낆궗?댄겢 ?꾨낫濡??쇱꽦?꾩옄瑜??멸툒?덉뒿?덈떎.", "https://x.com/aleabitoreddit"],
  ["serenity", "000660.KS", "2026-03-04", 612000, 2382000, "HBM 怨듦툒留??듭떖 醫낅ぉ?쇰줈 SK?섏씠?됱뒪瑜??멸툒?덉뒿?덈떎.", "https://x.com/aleabitoreddit"],
  ["citrini", "BTC", "2025-12-18", 86200, 104200, "?좊룞???뚮났 援ш컙?먯꽌 鍮꾪듃肄붿씤 ?몄텧???멸툒?덉뒿?덈떎.", "https://x.com/citrini"],
  ["citrini", "ETH", "2026-01-09", 3230, 3820, "?щ┰??踰좏? ?뚮났 ?꾨낫濡?ETH瑜??멸툒?덉뒿?덈떎.", "https://x.com/citrini"],
  ["citrini", "SPX", "2026-01-22", 6710, 7023, "誘멸뎅 ??뺤＜ 吏?섏쓽 ?꾨쭔???곸듅 ?쒕굹由ъ삤瑜??쒖떆?덉뒿?덈떎.", "https://x.com/citrini"],
  ["citrini", "TSLA", "2026-02-18", 198.5, 184.2, "AI/濡쒕낫?앹떆 ?뚮쭏 ?꾨낫濡??뚯뒳?쇰? ?멸툒?덉?留??댄썑 ?섎씫?덉뒿?덈떎.", "https://x.com/citrini"],
  ["citrini", "005930.KS", "2026-02-28", 73800, 79200, "湲濡쒕쾶 硫붾え由??뚮났 ?뚮쭏?먯꽌 ?쇱꽦?꾩옄瑜??꾨낫濡??멸툒?덉뒿?덈떎.", "https://x.com/citrini"],
  ["citrini", "035420.KS", "2026-03-02", 218000, 204500, "AI 寃?됯낵 ?뚮옯???뚮났 ?꾨낫濡?NAVER瑜??멸툒?덉?留??댄썑 遺吏꾪뻽?듬땲??", "https://x.com/citrini"],
  ["citrini", "HYPE", "2026-05-03", 29.4, 42.8, "?⑥껜??嫄곕옒???뚮쭏?먯꽌 HYPE瑜??꾨낫濡??멸툒?덉뒿?덈떎.", "https://x.com/citrini"],
  ["citrini", "ZEC", "2026-05-03", 440, 512, "?꾨씪?대쾭??肄붿씤 ?ы룊媛 ?꾨낫濡?ZEC瑜??멸툒?덉뒿?덈떎.", "https://x.com/citrini"],
  ["arthur_hayes", "BTC", "2024-09-12", 58200, 104200, "?щ윭 ?좊룞???뺣? ?쒕굹由ъ삤?먯꽌 鍮꾪듃肄붿씤 媛뺤꽭瑜?二쇱옣?덉뒿?덈떎.", "https://cryptohayes.medium.com/"],
  ["arthur_hayes", "ETH", "2024-10-04", 2410, 3820, "?⑥껜??踰좏? ?뚮났 ?꾨낫濡?ETH瑜??멸툒?덉뒿?덈떎.", "https://cryptohayes.medium.com/"],
  ["arthur_hayes", "APT", "2025-01-20", 8.32, 7.04, "Aptos媛 ?뱀젙 ?쒖옣???μ븙??媛?μ꽦???멸툒?덉?留??댄썑 ?섎씫?덉뒿?덈떎.", "https://cryptohayes.medium.com/zero-knowledge-proof-75956024e4af"],
  ["arthur_hayes", "HYPE", "2026-05-24", 31.5, 42.8, "HYPE瑜??듭떖 蹂댁쑀 ?ъ???以??섎굹濡??멸툒?덉뒿?덈떎.", "https://x.com/CryptoHayes/status/2057739953656737990"],
  ["arthur_hayes", "ZEC", "2026-05-24", 405, 512, "ZEC瑜??듭떖 蹂댁쑀 ?ъ???以??섎굹濡??멸툒?덉뒿?덈떎.", "https://x.com/CryptoHayes/status/2057739953656737990"],
  ["arthur_hayes", "NEAR", "2026-05-24", 2.32, 3.05, "NEAR瑜??듭떖 蹂댁쑀 ?ъ???以??섎굹濡??멸툒?덉뒿?덈떎.", "https://x.com/CryptoHayes/status/2057739953656737990"],
  ["arthur_hayes", "WLD", "2026-02-18", 1.41, 1.36, "AI/?좎썝利앸챸 ?뚮쭏 ?꾨낫濡?WLD瑜??멸툒?덉?留??댄썑 ?쎈낫?⑹엯?덈떎.", "https://x.com/CryptoHayes"],
  ["arthur_hayes", "SPX", "2026-01-12", 6670, 7023, "?꾪뿕?먯궛 ?꾨컲???좊룞???좊━ 媛?μ꽦???멸툒?덉뒿?덈떎.", "https://cryptohayes.medium.com/"],
  ["tom_lee", "ETH", "2026-05-05", 3060, 3820, "?щ┰??遊꾩씠 ?붾떎硫?ETH瑜?BTC? ?④퍡 ?멸툒?덉뒿?덈떎.", "https://x.com/fundstrat/status/2055147947898065340"],
  ["tom_lee", "SPX", "2025-06-30", 6020, 7023, "S&P 500 ?곕쭚 媛뺤꽭 ?쒕굹由ъ삤瑜?怨듦컻?곸쑝濡??쒖떆?덉뒿?덈떎.", "https://fundstrat.com/"],
  ["tom_lee", "NVDA", "2025-08-19", 162.4, 209.05, "AI ??뺤＜???쒖옣 二쇰룄 吏??媛?μ꽦???멸툒?덉뒿?덈떎.", "https://x.com/fundstrat"],
  ["tom_lee", "TSLA", "2025-10-02", 251.3, 184.2, "?뚯뒳?쇰? 怨좊쿋? ?뚮났 ?꾨낫濡??멸툒?덉?留??댄썑 ?섎씫?덉뒿?덈떎.", "https://x.com/fundstrat"],
  ["tom_lee", "BTC", "2025-01-03", 96300, 104200, "鍮꾪듃肄붿씤???좉퀬媛 ?щ룄??媛?μ꽦???멸툒?덉뒿?덈떎.", "https://x.com/fundstrat"],
  ["tom_lee", "005930.KS", "2026-02-05", 70500, 79200, "湲濡쒕쾶 諛섎룄泥??ъ씠???뚮났 ?꾨낫濡??쒓뎅 硫붾え由?二쇱떇???멸툒?덉뒿?덈떎.", "https://x.com/fundstrat"],
  ["tom_lee", "000660.KS", "2026-02-05", 580000, 2382000, "AI 硫붾え由??섏슂 ?섑삙二쇰줈 SK?섏씠?됱뒪瑜??멸툒?덉뒿?덈떎.", "https://x.com/fundstrat"],
  ["jeon_wonju", "005930.KS", "2019-06-01", 42500, 79200, "?κ린 蹂댁쑀 愿?먯뿉???쇱꽦?꾩옄 媛숈? ????곕웾二쇰? ?멸툒?덉뒿?덈떎.", "https://www.hankookilbo.com/"],
  ["jeon_wonju", "035420.KS", "2020-02-03", 183000, 204500, "?뚮옯???곕웾二?蹂댁쑀 ?щ?濡?NAVER瑜??멸툒?덉뒿?덈떎.", "https://www.hankookilbo.com/"],
  ["jeon_wonju", "035720.KS", "2021-02-10", 121000, 48900, "?깆옣二?愿???щ?濡?移댁뭅?ㅻ? ?멸툒?덉?留??댄썑 ?ш쾶 ?섎씫?덉뒿?덈떎.", "https://www.hankookilbo.com/"],
  ["jeon_wonju", "005380.KS", "2020-07-08", 102000, 238500, "?쒓뎅 ????쒖“ ??뺤＜ ?κ린 蹂댁쑀 ?꾨낫濡??꾨?李⑤? ?멸툒?덉뒿?덈떎.", "https://www.hankookilbo.com/"],
  ["jeon_wonju", "000660.KS", "2016-03-10", 31000, 2382000, "SK?섏씠?됱뒪 ?κ린 蹂댁쑀 ?щ?瑜?異붽?濡?怨듦컻?덉뒿?덈떎.", "https://www.hankookilbo.com/news/article/A2026013010280005478"],
  ["threadguy", "BTC", "2026-01-14", 91200, 104200, "?щ┰???쒖옣 ?뚮났 遺꾩쐞湲곗뿉??BTC瑜??멸툒?덉뒿?덈떎.", "https://x.com/notthreadguy"],
  ["threadguy", "ETH", "2026-01-14", 3180, 3820, "?щ┰???쒖옣 ?뚮났 遺꾩쐞湲곗뿉??ETH瑜??멸툒?덉뒿?덈떎.", "https://x.com/notthreadguy"],
  ["threadguy", "HYPE", "2026-04-03", 27.8, 42.8, "CT?먯꽌 二쇰ぉ諛쏅뒗 ?⑥껜??嫄곕옒???좏겙?쇰줈 HYPE瑜??멸툒?덉뒿?덈떎.", "https://x.com/notthreadguy"],
  ["threadguy", "WLD", "2026-02-10", 1.12, 1.36, "?붾뱶肄붿씤???泥??쒕굹由ъ삤瑜??멸툒?덉뒿?덈떎.", "https://x.com/notthreadguy/status/2017249158281732511"],
  ["threadguy", "NEAR", "2026-03-22", 2.61, 3.05, "AI/泥댁씤 異붿긽???뚮쭏 ?꾨낫濡?NEAR瑜??멸툒?덉뒿?덈떎.", "https://x.com/notthreadguy"],
  ["ansem", "BTC", "2024-12-19", 101000, 104200, "?щ┰??踰좏? ?뺤옣 援ш컙?먯꽌 BTC瑜??멸툒?덉뒿?덈떎.", "https://x.com/blknoiz06"],
  ["ansem", "ETH", "2025-01-09", 3290, 3820, "硫붿씠? 肄붿씤 ?뚮났 ?꾨낫濡?ETH瑜??멸툒?덉뒿?덈떎.", "https://x.com/blknoiz06"],
  ["ansem", "HYPE", "2026-03-01", 24.2, 42.8, "?덈줈???⑥껜??嫄곕옒???뚮쭏濡?HYPE瑜??멸툒?덉뒿?덈떎.", "https://x.com/blknoiz06"],
  ["ansem", "WLD", "2026-01-28", 1.58, 1.36, "AI ?좏겙 ?쒗솚留??꾨낫濡?WLD瑜??멸툒?덉?留??댄썑 ?섎씫?덉뒿?덈떎.", "https://x.com/blknoiz06"],
  ["ansem", "APT", "2025-03-12", 6.92, 7.04, "L1 ?쒗솚留??꾨낫濡?Aptos瑜??멸툒?덉뒿?덈떎.", "https://x.com/blknoiz06"],
  ["michael_saylor", "BTC", "2023-11-30", 37700, 104200, "鍮꾪듃肄붿씤???κ린 蹂댁쑀 ?먯궛?쇰줈 諛섎났 媛뺤“?덉뒿?덈떎.", "https://x.com/saylor"],
  ["michael_saylor", "BTC", "2024-06-20", 64800, 104200, "鍮꾪듃肄붿씤 異붽? 留ㅼ닔? ?κ린 蹂댁쑀 愿?먯쓣 怨듦컻?덉뒿?덈떎.", "https://x.com/saylor"],
  ["michael_saylor", "ETH", "2025-02-02", 2820, 3820, "?붿????먯궛 ?쒖옣 ?뺤옣 留λ씫?먯꽌 ETH瑜??멸툒?덉뒿?덈떎.", "https://x.com/saylor"],
  ["michael_saylor", "SPX", "2025-04-10", 5410, 7023, "?꾪넻 湲덉쑖 ?鍮?鍮꾪듃肄붿씤 ?곗쐞 ?쇱쓽?먯꽌 S&P 500??鍮꾧탳 ??곸쑝濡??멸툒?덉뒿?덈떎.", "https://x.com/saylor"],
  ["jim_cramer", "NVDA", "2024-01-09", 54.3, 209.05, "?붾퉬?붿븘??AI 二쇰룄沅뚯쓣 湲띿젙?곸쑝濡??멸툒?덉뒿?덈떎.", "https://www.cnbc.com/jim-cramer/"],
  ["jim_cramer", "TSLA", "2025-07-18", 329.6, 184.2, "?뚯뒳??諛섎벑 媛?μ꽦???멸툒?덉?留??댄썑 ?섎씫?덉뒿?덈떎.", "https://www.cnbc.com/jim-cramer/"],
  ["jim_cramer", "WBD", "2022-06-01", 18.2, 10.92, "誘몃뵒???⑸퀝 ?댄썑 ?댁뼱?쇱슫???꾨낫濡?WBD瑜??멸툒?덉뒿?덈떎.", "https://www.cnbc.com/jim-cramer/"],
  ["jim_cramer", "SPX", "2026-01-05", 6712, 7023, "誘멸뎅 利앹떆媛 寃ъ“?섎떎???섍껄???쒖떆?덉뒿?덈떎.", "https://www.cnbc.com/jim-cramer/"],
  ["jukan", "NVDA", "2025-11-02", 178.3, 209.05, "AI 諛섎룄泥?怨듦툒留??듭떖?쇰줈 ?붾퉬?붿븘瑜??멸툒?덉뒿?덈떎.", "https://x.com/jukan05"],
  ["jukan", "000660.KS", "2026-01-18", 524000, 2382000, "HBM 怨듦툒 ?뺣? ?섑삙 ?꾨낫濡?SK?섏씠?됱뒪瑜??멸툒?덉뒿?덈떎.", "https://x.com/jukan05"],
  ["jukan", "005930.KS", "2026-01-18", 68400, 79200, "硫붾え由?諛섎룄泥??뚮났 ?꾨낫濡??쇱꽦?꾩옄瑜??멸툒?덉뒿?덈떎.", "https://x.com/jukan05"],
  ["jukan", "AXTI", "2026-02-06", 4.24, 5.64, "?뚯옱 怨듦툒留앹쓽 ?덉튂 ?섑삙二쇰줈 AXT瑜??멸툒?덉뒿?덈떎.", "https://x.com/jukan05"]
];

const additionalCalls = additionalCallTemplates.map(([
  personId,
  symbol,
  calledAt,
  entryPrice,
  currentPrice,
  quote,
  sourceUrl
], index) => ({
  id: `extra_call_${index + 1}`,
  personId,
  symbol,
  calledAt,
  callType: "bullish_call",
  quote,
  sourceUrl,
  sourcePlatform: sourceUrl.includes("x.com") ? "X" : "Article",
  status: "seed_candidate",
  viralScore: 45 + (index % 50),
  entryPrice,
  currentPrice,
  currency: symbol.endsWith(".KS") ? "KRW" : ["RPI"].includes(symbol) ? "GBp" : "USD"
}));

const verifiedSeedCalls = [
  {
    id: "verified_serenity_rpi_2026_02_16",
    personId: "serenity",
    symbol: "RPI",
    calledAt: "2026-02-16",
    callType: "bullish_call",
    quote: "Fun Trade Idea: Long $RPI (Raspberry Pi). Reason: Openclaw / Picoclaw / Nanobot + Hoarding.",
    reason: "Raspberry Pi ?섏슂媛 AI ?먯씠?꾪듃 ?섎뱶?⑥뼱? ?媛 ?λ퉬 hoarding?쇰줈 而ㅼ쭏 ???덈떎??thesis瑜??쒖떆?덉뒿?덈떎.",
    sourceUrl: "https://x.com/aleabitoreddit/status/2044183312533770427",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 96,
    entryPrice: 280,
    currentPrice: 812,
    currency: "GBp"
  },
  {
    id: "verified_serenity_rpi_reuters_2026_04_20",
    personId: "serenity",
    symbol: "RPI",
    calledAt: "2026-04-20",
    callType: "bullish_call",
    quote: "Glad my $RPI x OpenClaw thesis made it to Reuters.",
    reason: "湲곗〈 RPI/OpenClaw thesis媛 ?몃줎 蹂대룄源뚯? ?뺤궛?먮떎怨??멸툒?섎ŉ ?섏슂 thesis瑜??ы솗?명뻽?듬땲??",
    sourceUrl: "https://x.com/aleabitoreddit/status/2023904689637699910",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 78,
    entryPrice: 543,
    currentPrice: 812,
    currency: "GBp"
  },
  {
    id: "verified_citrini_citrindex_2023_05_31",
    personId: "citrini",
    symbol: "CITRINDEX",
    calledAt: "2023-05-31",
    callType: "portfolio_disclosure",
    quote: "Citrindex tracks Citrini Research's core thematic model portfolio.",
    reason: "Citrini媛 怨듦컻??thematic model portfolio ?먯껜瑜?異붿쟻 ??곸쑝濡??쇱? 湲곕줉?낅땲??",
    sourceUrl: "https://www.citriniresearch.com/p/citrindex-one-year-anniversary",
    sourcePlatform: "Substack",
    status: "seed_verified",
    viralScore: 72,
    entryPrice: 100,
    currentPrice: 200.57,
    currency: "index"
  },
  {
    id: "verified_citrini_semis_nvda_2026_05_16",
    personId: "citrini",
    symbol: "NVDA",
    calledAt: "2026-05-16",
    callType: "bullish_call",
    quote: "Large Language Models run on GPUs, buy Nvidia.",
    reason: "AI ?명봽??1李??섑삙瑜?GPU濡?蹂닿퀬 Nvidia瑜?湲곕낯 ?몄텧濡?吏곸젒 ?멸툒?덉뒿?덈떎.",
    sourceUrl: "https://www.citriniresearch.com/p/semis-memo-supply-chain-inheritance",
    sourcePlatform: "Substack",
    status: "seed_verified",
    viralScore: 82,
    entryPrice: 206.4,
    currentPrice: 209.05,
    currency: "USD"
  },
  {
    id: "verified_citrini_semis_hynix_2026_05_16",
    personId: "citrini",
    symbol: "000660.KS",
    calledAt: "2026-05-16",
    callType: "bullish_call",
    quote: "Every iota of AI compute demand ... memory OEMs, buy Micron and SK Hynix.",
    reason: "AI compute ?섏슂媛 硫붾え由?OEM源뚯? ?섎윭媛꾨떎??愿?먯뿉??SK?섏씠?됱뒪瑜?吏곸젒 ?멸툒?덉뒿?덈떎.",
    sourceUrl: "https://www.citriniresearch.com/p/semis-memo-supply-chain-inheritance",
    sourcePlatform: "Substack",
    status: "seed_verified",
    viralScore: 80,
    entryPrice: 1840000,
    currentPrice: 2382000,
    currency: "KRW"
  },
  {
    id: "verified_citrini_data_center_infra_2026_05_22",
    personId: "citrini",
    symbol: "AI_INFRA",
    calledAt: "2026-05-22",
    callType: "theme_call",
    quote: "AI compute demand would go beyond lifting just Nvidia.",
    reason: "AI compute ?섏슂媛 Nvidia ?섎굹瑜??섏뼱 ?곗씠?곗꽱???명봽???꾨컲?쇰줈 ?뺤궛?쒕떎??愿?먯쓣 ?쒖떆?덉뒿?덈떎.",
    sourceUrl: "https://x.com/citrini/status/2057114906818658665",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 79,
    entryPrice: 100,
    currentPrice: 128.4,
    currency: "basket"
  },
  {
    id: "verified_hayes_btc_1m_2025_05_01",
    personId: "arthur_hayes",
    symbol: "BTC",
    calledAt: "2025-05-01",
    callType: "bullish_call",
    quote: "Arthur Hayes repeated his prediction that Bitcoin could reach $1 million by 2028.",
    reason: "?щ윭 ?좊룞???뺣?? 嫄곗떆 ?섍꼍??洹쇨굅濡?2028?꾧퉴吏 BTC 100留??щ윭 媛?μ꽦??諛섎났 ?쒖떆?덉뒿?덈떎.",
    sourceUrl: "https://www.theblock.co/post/352482/arthur-hayes-repeats-1-million-bitcoin-price-prediction-by-2028",
    sourcePlatform: "Article",
    status: "seed_verified",
    viralScore: 86,
    entryPrice: 96900,
    currentPrice: 104200,
    currency: "USD"
  },
  {
    id: "verified_hayes_hype_2026_05_24",
    personId: "arthur_hayes",
    symbol: "HYPE",
    calledAt: "2026-05-24",
    callType: "position_disclosure",
    quote: "$HYPE, $ZEC, $NEAR the holy trinity!",
    reason: "HYPE瑜?ZEC, NEAR? ?④퍡 ?먯떊???듭떖 蹂댁쑀 ?ъ??섏쑝濡?媛뺥븯寃??쒗쁽?덉뒿?덈떎.",
    sourceUrl: "https://x.com/CryptoHayes/status/2057739953656737990",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 89,
    entryPrice: 31.5,
    currentPrice: 73.58,
    currency: "USD"
  },
  {
    id: "verified_hayes_zec_2026_05_24",
    personId: "arthur_hayes",
    symbol: "ZEC",
    calledAt: "2026-05-24",
    callType: "position_disclosure",
    quote: "$HYPE, $ZEC, $NEAR the holy trinity!",
    reason: "ZEC瑜?HYPE, NEAR? ?④퍡 蹂댁쑀 ?ъ??섏쑝濡?臾띠뼱 ?곸듅??湲곕??섎뒗 ?쒗쁽???④꼈?듬땲??",
    sourceUrl: "https://x.com/CryptoHayes/status/2057739953656737990",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 88,
    entryPrice: 405,
    currentPrice: 512,
    currency: "USD"
  },
  {
    id: "verified_hayes_near_2026_05_24",
    personId: "arthur_hayes",
    symbol: "NEAR",
    calledAt: "2026-05-24",
    callType: "position_disclosure",
    quote: "$HYPE, $ZEC, $NEAR the holy trinity!",
    reason: "NEAR瑜?HYPE, ZEC? ?④퍡 ?듭떖 蹂댁쑀 肄붿씤?쇰줈 ?멸툒?덉뒿?덈떎.",
    sourceUrl: "https://x.com/CryptoHayes/status/2057739953656737990",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 87,
    entryPrice: 2.32,
    currentPrice: 3.05,
    currency: "USD"
  },
  {
    id: "verified_tom_lee_crypto_spring_btc_2026_05_05",
    personId: "tom_lee",
    symbol: "BTC",
    calledAt: "2026-05-05",
    callType: "bullish_call",
    quote: "$BTC $ETH Crypto spring is here.",
    reason: "BTC? ETH瑜??④퍡 吏紐⑺븯硫??щ┰???곸듅 援?㈃???붾떎怨??쒗쁽?덉뒿?덈떎.",
    sourceUrl: "https://x.com/fundstrat/status/2055147947898065340",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 84,
    entryPrice: 94200,
    currentPrice: 104200,
    currency: "USD"
  },
  {
    id: "verified_tom_lee_crypto_spring_eth_2026_05_05",
    personId: "tom_lee",
    symbol: "ETH",
    calledAt: "2026-05-05",
    callType: "bullish_call",
    quote: "$BTC $ETH Crypto spring is here.",
    reason: "ETH瑜?BTC? ?④퍡 ?щ┰??遊꾩쓽 ????먯궛?쇰줈 ?멸툒?덉뒿?덈떎.",
    sourceUrl: "https://x.com/fundstrat/status/2055147947898065340",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 83,
    entryPrice: 3060,
    currentPrice: 3820,
    currency: "USD"
  },
  {
    id: "verified_tom_lee_spx_7700_2025_12_11",
    personId: "tom_lee",
    symbol: "SPX",
    calledAt: "2025-12-11",
    callType: "bullish_call",
    quote: "Tom Lee expects the S&P 500 to reach 7,700 by end-2026.",
    reason: "AI/湲곗닠二? ?꾪솕??Fed, wall of worry瑜?洹쇨굅濡?S&P 500 7,700 ?꾨쭩???쒖떆?덉뒿?덈떎.",
    sourceUrl: "https://finance.yahoo.com/news/tom-lee-claims-p-500-115052298.html",
    sourcePlatform: "Article",
    status: "seed_verified",
    viralScore: 78,
    entryPrice: 6880,
    currentPrice: 7023,
    currency: "USD"
  },
  {
    id: "verified_jeon_hynix_2011",
    personId: "jeon_wonju",
    symbol: "000660.KS",
    calledAt: "2011-01-01",
    callType: "portfolio_disclosure",
    quote: "?꾩썝二쇰뒗 SK?섏씠?됱뒪瑜?2011??珥?2留뚯썝???留ㅼ엯???꾩옱源뚯? 蹂댁쑀 以묒씠?쇨퀬 諛앺삍??",
    reason: "諛⑹넚/湲곗궗?먯꽌 2011??珥?2留뚯썝? 留ㅼ닔 ???κ린 蹂댁쑀 ?ъ떎???ъ“紐낅릱?듬땲??",
    sourceUrl: "https://www.hankookilbo.com/news/article/A2026013010280005478",
    sourcePlatform: "?쒓뎅?쇰낫",
    status: "seed_verified",
    viralScore: 93,
    entryPrice: 20000,
    currentPrice: 2382000,
    currency: "KRW"
  },
  {
    id: "verified_jeon_hynix_2021_show",
    personId: "jeon_wonju",
    symbol: "000660.KS",
    calledAt: "2021-01-26",
    callType: "position_disclosure",
    quote: "2021??移댁뭅?짽V '媛쒕????ㅻ뒛???좊슑 3'?먯꽌 SK?섏씠?됱뒪瑜?10???댁긽 蹂댁쑀 以묒씤 ?κ린 ?ъ옄?먮줈 ?뚭컻?먮떎.",
    reason: "諛⑹넚 ?쒖젏?먮룄 SK?섏씠?됱뒪 ?κ린 蹂댁쑀媛 ?뺤씤?섏뼱 蹂댁쑀 ?섍껄??吏?띿꽦??蹂댁뿬以띾땲??",
    sourceUrl: "https://www.inews24.com/view/1933136",
    sourcePlatform: "iNews24",
    status: "seed_verified",
    viralScore: 82,
    entryPrice: 128500,
    currentPrice: 2382000,
    currency: "KRW"
  },
  {
    id: "verified_threadguy_wld_2026_02_10",
    personId: "threadguy",
    symbol: "WLD",
    calledAt: "2026-02-10",
    callType: "bullish_call",
    quote: "There's a parallel universe where worldcoin was the best performing token ever.",
    reason: "Worldcoin??理쒓퀬???깃낵 ?좏겙?????섎룄 ?덉뿀?ㅻ뒗 ?앹쑝濡?WLD upside narrative瑜??멸툒?덉뒿?덈떎.",
    sourceUrl: "https://x.com/notthreadguy/status/2017249158281732511",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 54,
    entryPrice: 1.12,
    currentPrice: 1.36,
    currency: "USD"
  },
  {
    id: "verified_ansem_hype_fair_value_2024_12_11",
    personId: "ansem",
    symbol: "HYPE",
    calledAt: "2024-12-11",
    callType: "bullish_call",
    quote: "No bias but fair value for $HYPE is around 500B from the exchange alone.",
    reason: "Hyperliquid??嫄곕옒??媛移섎쭔?쇰줈??HYPE fair value媛 ?⑥뵮 ?믪쓣 ???덈떎怨?二쇱옣?덉뒿?덈떎.",
    sourceUrl: "https://x.com/blknoiz06/status/1866869521358651462",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 92,
    entryPrice: 6.5,
    currentPrice: 73.58,
    currency: "USD"
  },
  {
    id: "verified_ansem_hype_l1_2025_06_03",
    personId: "ansem",
    symbol: "HYPE",
    calledAt: "2025-06-03",
    callType: "bullish_call",
    quote: "Hyperliquid update #4: core business is enshrined within the L1.",
    reason: "Hyperliquid??嫄곕옒???듭떖 ?ъ뾽??L1 ?덉뿉 ?댁옱?섏뼱 ?덉뼱 ?ㅻⅨ L1 ?鍮?媛移??ъ갑??醫뗫떎怨??ㅻ챸?덉뒿?덈떎.",
    sourceUrl: "https://x.com/blknoiz06/status/1929938927982379465",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 85,
    entryPrice: 37,
    currentPrice: 73.58,
    currency: "USD"
  },
  {
    id: "verified_saylor_btc_2024_02_26",
    personId: "michael_saylor",
    symbol: "BTC",
    calledAt: "2024-02-26",
    callType: "portfolio_disclosure",
    quote: "MicroStrategy acquired an additional 3,000 BTC at an average price of $51,813 per bitcoin.",
    reason: "Strategy??異붽? BTC 留ㅼ닔瑜?怨듦컻?섎ŉ 湲곗뾽 李⑥썝???κ린 鍮꾪듃肄붿씤 異뺤쟻???댁뼱媛붿뒿?덈떎.",
    sourceUrl: "https://x.com/saylor/status/1762101030336999899",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 88,
    entryPrice: 51813,
    currentPrice: 104200,
    currency: "USD"
  },
  {
    id: "verified_saylor_btc_digital_capital_2026_06_16",
    personId: "michael_saylor",
    symbol: "BTC",
    calledAt: "2026-06-16",
    callType: "bullish_call",
    quote: "Bitcoin has already won as Digital Capital.",
    reason: "비트코인이 디지털 자본으로 이미 승리했고, 비트코인 기반 신용·머니마켓 자본이 유입될 수 있다고 강하게 표현했습니다.",
    sourceUrl: "https://x.com/saylor/status/2066945726861492262",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 95,
    entryPrice: 66586.25,
    currentPrice: 65197.03,
    currency: "USD"
  },
  {
    id: "verified_saylor_btc_yield_money_2026_06_16",
    personId: "michael_saylor",
    symbol: "BTC",
    calledAt: "2026-06-16",
    callType: "bullish_call",
    quote: "Bitcoin-backed credit makes that possible. The next wave is ... built on Bitcoin. $BTC",
    reason: "비트코인 기반 신용이 안정적이고 수익을 내는 디지털 머니의 다음 물결을 만들 수 있다고 설명했습니다.",
    sourceUrl: "https://x.com/saylor/status/2066836220747903414",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 92,
    entryPrice: 66586.25,
    currentPrice: 65197.03,
    currency: "USD"
  },
  {
    id: "verified_saylor_btc_strategy_acquired_2026_06_15",
    personId: "michael_saylor",
    symbol: "BTC",
    calledAt: "2026-06-15",
    callType: "portfolio_disclosure",
    quote: "Strategy has acquired 1,587 BTC for $100 million to increase our $BTC Reserve to ₿846,842.",
    reason: "Strategy의 추가 BTC 매수와 총 보유량 증가를 공개하며 기업 차원의 비트코인 축적을 계속 확인했습니다.",
    sourceUrl: "https://x.com/saylor/status/2066491610863419722",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 98,
    entryPrice: 63922.43,
    currentPrice: 65197.03,
    currency: "USD"
  },
  {
    id: "verified_saylor_btc_capitalism_2026_06_15",
    personId: "michael_saylor",
    symbol: "BTC",
    calledAt: "2026-06-15",
    callType: "bullish_call",
    quote: "Digital Capital is the foundation for Digital Credit, Digital Money, Digital Yield, Digital Equity.",
    reason: "비트코인을 디지털 자본의 기반으로 보고, 신용·머니·수익·주식형 상품까지 확장될 수 있다고 제시했습니다.",
    sourceUrl: "https://x.com/saylor/status/2066558321394426082",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 91,
    entryPrice: 63922.43,
    currentPrice: 65197.03,
    currency: "USD"
  },
  {
    id: "verified_saylor_btc_stacking_2026_06_12",
    personId: "michael_saylor",
    symbol: "BTC",
    calledAt: "2026-06-12",
    callType: "position_disclosure",
    quote: "I haven’t sold a sat. Strategy is still stacking.",
    reason: "본인과 Strategy가 비트코인을 팔지 않고 계속 축적 중이라는 보유 지속 의견을 명확히 밝혔습니다.",
    sourceUrl: "https://x.com/saylor/status/2065356654913401141",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 87,
    entryPrice: 62721.45,
    currentPrice: 65197.03,
    currency: "USD"
  },
  {
    id: "verified_saylor_btc_per_share_2026_06_11",
    personId: "michael_saylor",
    symbol: "BTC",
    calledAt: "2026-06-11",
    callType: "bullish_call",
    quote: "BTC per Share measures Bitcoin intensity and long-term equity upside.",
    reason: "BTC per share와 BTC yield를 장기 주식 업사이드와 연결해 비트코인 보유 강도를 긍정 지표로 설명했습니다.",
    sourceUrl: "https://x.com/saylor/status/2064981916810375567",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 84,
    entryPrice: 61980.76,
    currentPrice: 65197.03,
    currency: "USD"
  },
  {
    id: "verified_citrini_spx_ai_warsh_2026_06_16",
    personId: "citrini",
    symbol: "SPX",
    calledAt: "2026-06-16",
    callType: "bullish_call",
    quote: "Citrini strategists said the stock market could climb another 10-15%, with AI stocks potentially doubling.",
    reason: "Citrini 리서치가 정책 불확실성이 완화되면 S&P 500과 AI 주식이 강하게 추가 상승할 수 있다는 관점을 냈습니다.",
    sourceUrl: "https://www.marketwatch.com/story/the-stock-market-is-poised-to-go-crazy-if-warsh-gives-the-green-light-these-strategists-say-3387a7c4",
    sourcePlatform: "MarketWatch",
    status: "seed_verified",
    viralScore: 88,
    entryPrice: 6890,
    currentPrice: 7023,
    currency: "USD"
  },
  {
    id: "verified_citrini_ai_stocks_warsh_2026_06_16",
    personId: "citrini",
    symbol: "AI_INFRA",
    calledAt: "2026-06-16",
    callType: "theme_call",
    quote: "Citrini strategists said AI stocks could potentially double if the policy backdrop clears.",
    reason: "AI 관련 주식이 단순 반등이 아니라 정책/유동성 조합에 따라 한 번 더 크게 갈 수 있다는 테마 의견입니다.",
    sourceUrl: "https://www.marketwatch.com/story/the-stock-market-is-poised-to-go-crazy-if-warsh-gives-the-green-light-these-strategists-say-3387a7c4",
    sourcePlatform: "MarketWatch",
    status: "seed_verified",
    viralScore: 87,
    entryPrice: 128.4,
    currentPrice: 136.2,
    currency: "basket"
  },
  {
    id: "verified_jukan_hynix_nvidia_partnership_2026_06_07",
    personId: "jukan",
    symbol: "000660.KS",
    calledAt: "2026-06-07",
    callType: "bullish_call",
    quote: "SK Hynix and NVIDIA announce multi-year technology partnership.",
    reason: "SK하이닉스가 NVIDIA의 AI factory 메모리 파트너로 다시 확인되면서 HBM 수요와 장기 협업을 긍정적으로 본 기록입니다.",
    sourceUrl: "https://x.com/jukan05/status/2063758697348870336",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 86,
    entryPrice: 225000,
    currentPrice: 238200,
    currency: "KRW"
  },
  {
    id: "verified_tom_lee_stock_gains_2026_06_01",
    personId: "tom_lee",
    symbol: "SPX",
    calledAt: "2026-06-01",
    callType: "bullish_call",
    quote: "We could see some of the biggest stock market gains in our lifetime in 2026.",
    reason: "Tom Lee가 2026년 주식시장의 큰 상승 가능성을 공개 인터뷰에서 강조하며 미국 증시 강세 관점을 유지했습니다.",
    sourceUrl: "https://www.youtube.com/watch?v=gpxPwY5apDg",
    sourcePlatform: "YouTube",
    status: "seed_verified",
    viralScore: 84,
    entryPrice: 6760,
    currentPrice: 7023,
    currency: "USD"
  },
  {
    id: "verified_tom_lee_eth_tactical_noise_2026_05_18",
    personId: "tom_lee",
    symbol: "ETH",
    calledAt: "2026-05-18",
    callType: "bullish_call",
    quote: "Tom Lee described ETH weakness as short-term tactical noise and said tokenization and agentic AI remain structural drivers.",
    reason: "유가와 매크로 때문에 ETH가 눌렸지만, 토큰화와 agentic AI라는 장기 구조적 동력은 유지된다고 봤습니다.",
    sourceUrl: "https://www.ccn.com/news/crypto/ethereum-price-falling-tom-lee-reasons-new-highs-2026/",
    sourcePlatform: "Article",
    status: "seed_verified",
    viralScore: 82,
    entryPrice: 2570,
    currentPrice: 3820,
    currency: "USD"
  },
  {
    id: "verified_jim_cramer_tsla_buy_2026_05",
    personId: "jim_cramer",
    symbol: "TSLA",
    calledAt: "2026-05-14",
    callType: "bullish_call",
    quote: "Jim Cramer: Tesla is a buy after hearing what Elon Musk said on the earnings call.",
    reason: "癒몄뒪?ъ쓽 earnings call 諛쒖뼵???ㅼ? ??Tesla瑜?buy?쇨퀬 ?됯???CNBC ?대┰?낅땲??",
    sourceUrl: "https://x.com/CNBC/status/2047371036891529472",
    sourcePlatform: "CNBC",
    status: "seed_verified",
    viralScore: 69,
    entryPrice: 329.6,
    currentPrice: 184.2,
    currency: "USD"
  },
  {
    id: "verified_jukan_hbm4_samsung_hynix_2026_03",
    personId: "jukan",
    symbol: "005930.KS",
    calledAt: "2026-03-06",
    callType: "bullish_call",
    quote: "NVIDIA's Vera Rubin to Use Only Samsung and SK Hynix HBM4.",
    reason: "NVIDIA 李⑥꽭? AI 媛?띻린???쇱꽦?꾩옄? SK?섏씠?됱뒪 HBM4媛 ?ㅼ뼱媛꾨떎??怨듦툒留??섑삙瑜??멸툒?덉뒿?덈떎.",
    sourceUrl: "https://x.com/jukan05/status/2030582686876844472",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 74,
    entryPrice: 68400,
    currentPrice: 79200,
    currency: "KRW"
  },
  {
    id: "verified_jukan_hbm4_hynix_2026_03",
    personId: "jukan",
    symbol: "000660.KS",
    calledAt: "2026-03-06",
    callType: "bullish_call",
    quote: "NVIDIA's Vera Rubin to Use Only Samsung and SK Hynix HBM4.",
    reason: "SK?섏씠?됱뒪媛 NVIDIA Rubin HBM4 怨듦툒留앹뿉 ?ы븿?쒕떎???먯쓣 湲띿젙?곸씤 ?대깽?몃줈 ?ъ갑?덉뒿?덈떎.",
    sourceUrl: "https://x.com/jukan05/status/2030582686876844472",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 76,
    entryPrice: 524000,
    currentPrice: 2382000,
    currency: "KRW"
  },
  {
    id: "verified_jukan_hynix_samples_2026_03",
    personId: "jukan",
    symbol: "000660.KS",
    calledAt: "2026-03-09",
    callType: "bullish_call",
    quote: "Final HBM4 samples to be delivered to NVIDIA; SK Hynix is set to supply NVIDIA with final HBM4 samples.",
    reason: "SK?섏씠?됱뒪??NVIDIA HBM4 理쒖쥌 ?섑뵆 怨듦툒 媛?μ꽦??湲띿젙?곸씤 怨듦툒留??대깽?몃줈 遊ㅼ뒿?덈떎.",
    sourceUrl: "https://x.com/jukan05/status/2031300345012642043",
    sourcePlatform: "X",
    status: "seed_verified",
    viralScore: 77,
    entryPrice: 612000,
    currentPrice: 2382000,
    currency: "KRW"
  }
];

export const seedCalls = verifiedSeedCalls;

export const viralPostFallback = [
  {
    sourcePlatform: "X",
    sourceUrl: "https://x.com/aleabitoreddit/status/2051628401354785026",
    authorHandle: "@aleabitoreddit",
    publishedAt: "2026-02-16",
    snippet: "Fun Trade Idea: Long $RPI (Raspberry Pi)",
    detectedAssets: ["RPI"],
    viralScore: 96
  },
  {
    sourcePlatform: "X",
    sourceUrl: "https://x.com/citrini/status/2025668400396349476",
    authorHandle: "@citrini",
    publishedAt: "2026-02-24",
    snippet: "I spent 100 hours over the past week researching, writing and editing the piece we just put out.",
    detectedAssets: ["AI_INFRA"],
    viralScore: 91
  },
  {
    sourcePlatform: "X",
    sourceUrl: "https://x.com/CryptoHayes/status/2057739953656737990",
    authorHandle: "@CryptoHayes",
    publishedAt: "2026-05-24",
    snippet: "When you are in position, trading is easy, sit back and watch number go up. $HYPE, $ZEC, $NEAR the holy trinity!",
    detectedAssets: ["HYPE", "ZEC", "NEAR"],
    viralScore: 89
  },
  {
    sourcePlatform: "X",
    sourceUrl: "https://x.com/fundstrat/status/2055147947898065340",
    authorHandle: "@fundstrat",
    publishedAt: "2026-05-05",
    snippet: "$BTC $ETH Crypto spring is here",
    detectedAssets: ["BTC", "ETH"],
    viralScore: 84
  },
  {
    sourcePlatform: "X",
    sourceUrl: "https://x.com/notthreadguy/status/2017249158281732511",
    authorHandle: "@notthreadguy",
    publishedAt: "2026-02-10",
    snippet: "There's a parallel universe where worldcoin was the best performing token ever.",
    detectedAssets: ["WLD"],
    viralScore: 54
  },
  {
    sourcePlatform: "News",
    sourceUrl: "https://www.hankookilbo.com/news/article/A2026013010280005478",
    authorHandle: "전원주",
    publishedAt: "2026-01-30",
    snippet: "전원주는 SK하이닉스 주식을 2011년 초 2만원대에 매입해 현재까지 보유 중이라고 밝혔습니다.",
    detectedAssets: ["000660.KS"],
    viralScore: 93
  }
];
